from DeanerySystem.lessonv3 import Lesson
from DeanerySystem.action import Action
from DeanerySystem.timetable1 import Timetable1
from DeanerySystem.timetable2 import Timetable2
from DeanerySystem.basicterm import BasicTerm
from DeanerySystem.basicterm import Term
from DeanerySystem.breakT import Break
from DeanerySystem.basictimetable import BasicTimetable
from DeanerySystem.day import Day